name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql+psycopg2://app_user:app_password@localhost:5432/app_db
      SECRET_KEY: your_secret_key_here
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30


    steps:
      - name: Copia os arquivos do repositório
        uses: actions/checkout@v3

      - name: Instalar o python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar o poetry
        run: pipx install poetry

      - name: Instalar dependências
        run: poetry install

      - name: Executar testes
        run: poetry run task test
